Repository MicrosoftDocs/visualstudio-docs.ko-kr, pull requests merged in 2019-12, with the labels that each got.

#82 Update how-to-move-around-in-the-visual-studio-ide.md
  docs/ide/how-to-move-around-in-the-visual-studio-ide.md
Labels: Linguistic Suggestion, Partially Accepted

#89 Update debugging-native-code.md
  docs/debugger/debugging-native-code.md
Labels: Accepted, Linguistic Suggestion

#90 Update debugging-preparation-visual-cpp-project-types.md
  docs/debugger/debugging-preparation-visual-cpp-project-types.md
Labels: Accepted, Linguistic Suggestion

#92 Update c-cpp-assertions.md
  docs/debugger/c-cpp-assertions.md
Labels: Accepted, Linguistic Suggestion

#91 Update debugbreak-and-debugbreak.md
  docs/debugger/debugbreak-and-debugbreak.md
Labels: Accepted, Source Issue

#95 Update crt-debug-library-use.md
  docs/debugger/crt-debug-library-use.md
Labels: Accepted, Technical Issue

#93 Update crt-debugging-techniques.md
  docs/debugger/crt-debugging-techniques.md
Labels: Accepted, Linguistic Suggestion

#96 Update debug-versions-of-heap-allocation-functions.md
  docs/debugger/debug-versions-of-heap-allocation-functions.md
Labels: Accepted, Linguistic Suggestion

#97 Update crt-debug-heap-details.md
  docs/debugger/crt-debug-heap-details.md
Labels: Accepted, Linguistic Suggestion

#98 Update debug-hook-function-writing.md
  docs/debugger/debug-hook-function-writing.md
Labels: Accepted, Linguistic Suggestion

#99 Update allocation-hook-functions.md
  docs/debugger/allocation-hook-functions.md
Labels: Accepted, Linguistic Suggestion

#105 Update how-can-i-debug-windows-api-functions-q.md
  docs/debugger/how-can-i-debug-windows-api-functions-q.md
Labels: Accepted, Linguistic Suggestion
