Repository MicrosoftDocs/visualstudio-docs.ko-kr, pull requests merged in 2019-10, with the labels that each got.

#55 Spell correction
  docs/javascript/tutorial-nodejs-with-react-and-jsx.md
Labels: Linguistic Suggestion, Partially Accepted

#59 몇가지 어색한 표현을 수정하였습니다.
  docs/debugger/write-better-code-with-visual-studio.md
Labels: Accepted, Linguistic Suggestion, Source Issue

#56 지나치게 어색한 표현을 수정하였습니다.
  docs/extensibility/walkthrough-creating-an-sdk-using-javascript.md
Labels: Accepted, Linguistic Suggestion
