Repository MicrosoftDocs/visualstudio-docs.ko-kr, pull requests merged in 2020-01, with the labels that each got.

#100 Update allocation-hooks-and-c-run-time-memory-allocations.md
  docs/debugger/allocation-hooks-and-c-run-time-memory-allocations.md
Labels: Accepted, Linguistic Suggestion

#101 Update finding-memory-leaks-using-the-crt-library.md
  docs/debugger/finding-memory-leaks-using-the-crt-library.md
Labels: Linguistic Suggestion, Partially Accepted, Technical Issue

#102 Better Korean Translation
  CONTRIBUTING.md
  docs/install/install-visual-studio.md
Labels: Linguistic Suggestion, Partially Accepted

#103 Update how-can-i-debug-an-access-violation-q.md
  docs/debugger/how-can-i-debug-an-access-violation-q.md
Labels: Linguistic Suggestion, Partially Accepted

#109 Update com-debugging-tools.md
  docs/debugger/com-debugging-tools.md
Labels: Accepted, Linguistic Suggestion

#111 Update debugging-gpu-code.md
  docs/debugger/debugging-gpu-code.md
Labels: Accepted

#104 Update how-can-i-use-debugger-windows-while-debugging-a-foreground-pr…
  docs/debugger/how-can-i-use-debugger-windows-while-debugging-a-foreground-program-q.md
Labels: Accepted, Linguistic Suggestion

#106 Update how-to-get-back-to-the-function-that-called-mfc-if-halted.md
  docs/debugger/how-to-get-back-to-the-function-that-called-mfc-if-halted.md
Labels: Accepted, Linguistic Suggestion

#107 Update com-and-activex-debugging.md
  docs/debugger/com-and-activex-debugging.md
Labels: Accepted, Linguistic Suggestion

#108 Update debugging-a-data-bound-activex-control.md
  docs/debugger/debugging-a-data-bound-activex-control.md
Labels: Accepted, Linguistic Suggestion

#110 Update how-to-debug-injected-code.md
  docs/debugger/how-to-debug-injected-code.md
Labels: Accepted, Linguistic Suggestion

#112 Update visual-studio-graphics-diagnostics.md
  docs/debugger/graphics/visual-studio-graphics-diagnostics.md
Labels: Accepted, Linguistic Suggestion

#114 Update overview-of-visual-studio-graphics-diagnostics.md
  docs/debugger/graphics/overview-of-visual-studio-graphics-diagnostics.md
Labels: Linguistic Suggestion, Partially Accepted

#115 Update getting-started-with-visual-studio-graphics-diagnostics.md
  docs/debugger/graphics/getting-started-with-visual-studio-graphics-diagnostics.md
Labels: Linguistic Suggestion, Partially Accepted

#116 Update capturing-graphics-information.md
  docs/debugger/graphics/capturing-graphics-information.md
Labels: Accepted, Linguistic Suggestion
